name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache npm dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm run test
