name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: install pnpm
        run: npm install -g pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Run Tests
        run: pnpm test
